version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/redis"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/bbolt"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/memcached"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/examples"
    schedule:
      interval: "daily"
